const moodboardImages = [
    "images/moodboard/1.jpg",
    "images/moodboard/2.jpg",
    "images/moodboard/3.jpg",
    "images/moodboard/4.jpg",
    "images/moodboard/5.jpg",
    "images/moodboard/6.jpg",
    "images/moodboard/7.jpg",
    "images/moodboard/8.jpg",
    "images/moodboard/9.jpg",
    "images/moodboard/10.jpg",
    "images/moodboard/11.jpg",
    "images/moodboard/12.jpg",
    "images/moodboard/13.jpg",
    "images/moodboard/14.jpg",
    "images/moodboard/15.jpg",
    "images/moodboard/16.jpg",
    "images/moodboard/17.jpg",
    "images/moodboard/18.jpg",
    "images/moodboard/19.jpg",
    "images/moodboard/20.jpg",
    "images/moodboard/21.jpg",
    "images/moodboard/22.jpg",
    "images/moodboard/23.jpg",
    "images/moodboard/24.jpg",
    "images/moodboard/25.jpg",
    "images/moodboard/26.jpg",
    "images/moodboard/27.jpg",
    "images/moodboard/28.jpg",
    "images/moodboard/29.jpg",
    "images/moodboard/30.jpg",
    "images/moodboard/31.jpg",
    "images/moodboard/32.jpg",
    "images/moodboard/33.jpg",
    "images/moodboard/34.jpg",
    "images/moodboard/35.jpg",
    "images/moodboard/36.jpg",
    "images/moodboard/37.jpg",
    "images/moodboard/38.jpg",
    "images/moodboard/39.jpg",
    "images/moodboard/40.jpg",
    "images/moodboard/41.jpg",
    "images/moodboard/42.jpg",
    "images/moodboard/43.jpg",
    "images/moodboard/44.jpg",
    "images/moodboard/45.jpg",
    "images/moodboard/46.jpg",
    "images/moodboard/47.jpg",
    "images/moodboard/48.jpg",
    "images/moodboard/49.jpg",
    "images/moodboard/50.jpg"
];

const styleImages = [
    "images/style/1.jpg",
    "images/style/2.jpg",
    "images/style/3.jpg",
    "images/style/4.jpg",
    "images/style/5.jpg",
    "images/style/6.jpg",
    "images/style/7.jpg",
    "images/style/8.jpg",
    "images/style/9.jpg",
    "images/style/10.jpg",
    "images/style/11.jpg",
    "images/style/12.jpg",
    "images/style/13.jpg",
    "images/style/14.jpg",
    "images/style/15.jpg",
    "images/style/16.jpg",
    "images/style/17.jpg",
    "images/style/18.jpg",
    "images/style/19.jpg",
    "images/style/20.jpg",
    "images/style/21.jpg",
    "images/style/22.jpg",
    "images/style/23.jpg",
    "images/style/24.jpg",
    "images/style/25.jpg",
    "images/style/26.jpg",
    "images/style/27.jpg",
    "images/style/28.jpg",
    "images/style/29.jpg",
    "images/style/30.jpg",
    "images/style/31.jpg",
    "images/style/32.jpg",
    "images/style/33.jpg",
    "images/style/34.jpg",
    "images/style/35.jpg",
    "images/style/36.jpg",
    "images/style/37.jpg",
    "images/style/38.jpg",
    "images/style/39.jpg",
    "images/style/40.jpg",
    "images/style/41.jpg",
    "images/style/42.jpg",
    "images/style/43.jpg",
    "images/style/44.jpg",
    "images/style/45.jpg",
    "images/style/46.jpg",
    "images/style/47.jpg",
    "images/style/48.jpg",
    "images/style/49.jpg",
    "images/style/50.jpg"
];

const gothicImages = [
    "images/gothic/1.jpg",
    "images/gothic/2.jpg",
    "images/gothic/3.jpg",
    "images/gothic/4.jpg",
    "images/gothic/5.jpg",
    "images/gothic/6.jpg",
    "images/gothic/7.jpg",
    "images/gothic/8.jpg",
    "images/gothic/9.jpg",
    "images/gothic/10.jpg",
    "images/gothic/11.jpg",
    "images/gothic/12.jpg",
    "images/gothic/13.jpg",
    "images/gothic/14.jpg",
    "images/gothic/15.jpg",
    "images/gothic/16.jpg",
    "images/gothic/17.jpg",
    "images/gothic/18.jpg",
    "images/gothic/19.jpg",
    "images/gothic/20.jpg",
    "images/gothic/21.jpg",
    "images/gothic/22.jpg",
    "images/gothic/23.jpg",
    "images/gothic/24.jpg",
    "images/gothic/25.jpg",
    "images/gothic/26.jpg",
    "images/gothic/27.jpg",
    "images/gothic/28.jpg",
    "images/gothic/29.jpg",
    "images/gothic/30.jpg",
    "images/gothic/31.jpg",
    "images/gothic/32.jpg",
    "images/gothic/33.jpg",
    "images/gothic/34.jpg",
    "images/gothic/35.jpg",
    "images/gothic/36.jpg",
    "images/gothic/37.jpg",
    "images/gothic/38.jpg",
    "images/gothic/39.jpg",
    "images/gothic/40.jpg",
    "images/gothic/41.jpg",
    "images/gothic/42.jpg",
    "images/gothic/43.jpg",
    "images/gothic/44.jpg",
    "images/gothic/45.jpg",
    "images/gothic/46.jpg",
    "images/gothic/47.jpg",
    "images/gothic/48.jpg",
    "images/gothic/49.jpg",
    "images/gothic/50.jpg"

];

function randomImage(array) {
    return array[Math.floor(Math.random() * array.length)];
}

function generateImages() {
    document.getElementById("moodboard-img").src =
        randomImage(moodboardImages);

    document.getElementById("style-img").src =
        randomImage(styleImages);

    document.getElementById("gothic-img").src =
        randomImage(gothicImages);
}

generateImages();